"""
InsightGenie AI - Export Utilities
CSV/Excel export and chart image generation
"""

import pandas as pd
import io
from typing import Optional
import base64


def export_csv(df: pd.DataFrame) -> str:
    """Export DataFrame to CSV string."""
    return df.to_csv(index=False)


def export_excel(df: pd.DataFrame) -> bytes:
    """Export DataFrame to Excel bytes."""
    buffer = io.BytesIO()
    df.to_excel(buffer, index=False, engine='openpyxl')
    buffer.seek(0)
    return buffer.getvalue()


def get_download_link(df: pd.DataFrame, filename: str, file_type: str = "csv") -> str:
    """Generate a download link for the DataFrame."""
    if file_type == "csv":
        data = df.to_csv(index=False)
        b64 = base64.b64encode(data.encode()).decode()
        mime = "text/csv"
    else:
        data = export_excel(df)
        b64 = base64.b64encode(data).decode()
        mime = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    
    return f'<a href="data:{mime};base64,{b64}" download="{filename}">Download {filename}</a>'


def generate_report_summary(df: pd.DataFrame, insights: list) -> str:
    """Generate a text report summary."""
    report = []
    report.append("=" * 50)
    report.append("INSIGHTGENIE AI - DATA ANALYSIS REPORT")
    report.append("=" * 50)
    report.append("")
    report.append(f"Dataset Overview:")
    report.append(f"  - Total Records: {len(df)}")
    report.append(f"  - Total Columns: {len(df.columns)}")
    report.append(f"  - Columns: {', '.join(df.columns[:10])}")
    report.append("")
    
    numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns
    if len(numeric_cols) > 0:
        report.append("Numeric Summary:")
        for col in numeric_cols[:5]:
            report.append(f"  {col}:")
            report.append(f"    Mean: {df[col].mean():.2f}")
            report.append(f"    Median: {df[col].median():.2f}")
            report.append(f"    Std: {df[col].std():.2f}")
        report.append("")
    
    if insights:
        report.append("Key Insights:")
        for insight in insights:
            report.append(f"  - {insight.get('title', 'Insight')}: {insight.get('subtitle', '')}")
    
    report.append("")
    report.append("=" * 50)
    report.append("Generated by InsightGenie AI")
    report.append("=" * 50)
    
    return "\n".join(report)
